package com.tsd.auth.manager.utils;

public class SQLQuery {
	public static final String selAppUserWithMobile = "SELECT * FROM CUSTOMER WHERE EMAIL = ? OR MOBILE = ?",
	selAppUserWithId = "SELECT * FROM CUSTOMER WHERE ID = ?",
	selCusAdd = "SELECT * FROM ADDRESS WHERE CUSTOMER_ID=?",
	updCustProfile = "UPDATE CUSTOMER SET EMAIL = ?, FIRST_NAME = ?, LAST_NAME = ? WHERE ID = ?",
	creCusAdd = "INSERT INTO ADDRESS (CUSTOMER_ID,SHORT_NAME,LINE1,LINE2,LINE3,CITY,STATE_NAME,COUNTRY,PIN_CODE,GEO_TAG,IS_DEFAULT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
	updCustAddress = "UPDATE ADDRESS SET SHORT_NAME = ?,LINE1 = ?,LINE2 = ?,LINE3 = ?,CITY = ?,STATE_NAME = ?,COUNTRY = ?,PIN_CODE = ?,GEO_TAG = ?,IS_DEFAULT = ? WHERE CUSTOMER_ID = ? and ID = ?",
	
	selCatId = "SELECT CT.ID FROM CATALOG CT, CUSTOMER CU WHERE CU.DISTRIBUTOR_ID = CT.DISTRIBUTOR_ID AND CU.ID = ?",
	selPrd = "SELECT CL.ID LINE_ID,P.*,B.NAME BRAND,CL.DISCOUNT,P.MRP - CL.DISCOUNT PRICE,C.DISTRIBUTOR_ID,C.ID CATALOG_ID "
			+ "FROM CATALOG C," + "CATALOG_LINE CL," + "PRODUCT P," + "BRAND B "
			+ "WHERE C.ID = CL.CATALOG_ID AND CL.PRODUCT_ID = P.ID AND P.BRAND_ID = B.ID AND C.ID = ?",
	selCat = "SELECT DISTINCT CT.* " + "FROM CATEGORY CT, " + "CATALOG C,"
			+ "CATALOG_LINE CL," + "PRODUCT P "
			+ "WHERE C.ID = CL.CATALOG_ID AND CL.PRODUCT_ID = P.ID AND CT. NAME IN(P.PRODUCT_GROUP,P.CATEGORY,COALESCE(P.SUB_CATEGORY, '0')) AND C.ID = ? ORDER BY ID ASC",
	selBrands = "SELECT DISTINCT B.* FROM BRAND B,CATALOG C,CATALOG_LINE CL,PRODUCT P WHERE C.ID = CL.CATALOG_ID AND CL.PRODUCT_ID = P.ID AND P.BRAND_ID = B.ID AND C.ID = ? ORDER BY ID ASC",
	selVisibleSub = "SELECT * FROM SUBSCRIPTION WHERE CUSTOMER_ID=? AND (STOP IS NULL OR STOP > CURRENT_DATE) AND START < CURRENT_DATE + 30 AND VISIBLE = true",
	selSub = "SELECT * FROM SUBSCRIPTION WHERE ID=?",
	creSub = "INSERT INTO SUBSCRIPTION (CUSTOMER_ID,DISTRIBUTOR_ID,PRODUCT_ID,QUANTITY,TYPE,DAY_OF_WEEK,DAY_OF_MONTH,STATUS,START,STOP,PERMANENT,VISIBLE,PARENT_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",

	selCusOrd = "SELECT * FROM TSD.ORDER WHERE CUSTOMER_ID = ? AND ORDER_DATE BETWEEN CURRENT_DATE AND CURRENT_DATE + 30 ORDER BY ORDER_DATE ASC",
	selCusSub = "SELECT * FROM SUBSCRIPTION WHERE CUSTOMER_ID=? AND VISIBLE = true AND (STOP IS NULL OR STOP > CURRENT_DATE)",
	selActSub = "SELECT * FROM SUBSCRIPTION WHERE CUSTOMER_ID=? AND (STOP IS NULL OR STOP > CURRENT_DATE) AND START < CURRENT_DATE + 30",
	selCusOrdLines = "SELECT * FROM ORDER_LINE WHERE ORDER_ID IN (SELECT ORDER_ID FROM TSD.ORDER WHERE CUSTOMER_ID = ? AND ORDER_DATE BETWEEN CURRENT_DATE AND CURRENT_DATE + 30)",
	selCusDel = "SELECT * FROM TSD.ORDER WHERE CUSTOMER_ID = ? AND ORDER_DATE BETWEEN CURRENT_DATE - 30 AND CURRENT_DATE - 1 AND STATUS = 'D' ORDER BY ORDER_DATE DESC",
	selCusDelLines = "SELECT * FROM ORDER_LINE WHERE ORDER_ID IN (SELECT ORDER_ID FROM TSD.ORDER WHERE CUSTOMER_ID = ? AND ORDER_DATE BETWEEN CURRENT_DATE - 30 AND CURRENT_DATE - 1 AND STATUS = 'D')",
	creCus = "INSERT INTO CUSTOMER (EMAIL, MOBILE, FIRST_NAME, LAST_NAME, ACTIVE, DISTRIBUTOR_ID) VALUES (?, ?, ?, ?, ?, ?)",
	updCus = "UPDATE CUSTOMER SET EMAIL = ?, FIRST_NAME = ?, LAST_NAME = ? WHERE ID = ?",
	updCusAdd = "UPDATE ADDRESS SET SHORT_NAME = ?, LINE1 = ?, LINE2 = ?, LINE3 = ?, CITY = ?, STATE_NAME = ?, COUNTRY = ?, PIN_CODE = ?, GEO_TAG = ?, IS_DEFAULT = ? WHERE CUSTOMER_ID = ? and ID = ?",
	toggleDefault = "UPDATE ADDRESS SET IS_DEFAULT = false WHERE CUSTOMER_ID = ? and ID <> ?",
	selOrd = "SELECT * FROM TSD.ORDER WHERE ID=?",
	selOrdLine = "SELECT * FROM ORDER_LINE WHERE ORDER_ID =? AND ID = ?",
	selOrdLines = "SELECT * FROM ORDER_LINE WHERE ORDER_ID =?", 
	delOrdLn = "DELETE FROM ORDER_LINE WHERE ID =?",
	updOrdLn = "UPDATE ORDER_LINE SET QUANTITY = ? WHERE ID = ?",
	creOrder = "INSERT INTO ORDER (CUSTOMER_ID, ADDRESS_ID, STATUS, ORDER_DATE) VALUES (?, 1, 'N', ?)",
	creOrdLine = "INSERT INTO ORDER_LINE (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES (?, ?, ?)",
	selSubLines = "SELECT * FROM SUBSCRIPTION WHERE CUSTOMER_ID = ? AND (DAY_OF_MONTH ~ ? OR DAY_OF_WEEK ~ ?)";

}